"""Real initialization

Revision ID: 98adc92ce833
Revises: 
Create Date: 2026-05-22 16:30:16.889909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98adc92ce833'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cars', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('cars_owner_id_fkey'), 'cars', type_='foreignkey')
    op.create_foreign_key(None, 'cars', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('parts', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('parts_record_id_fkey'), 'parts', type_='foreignkey')
    op.create_foreign_key(None, 'parts', 'service_records', ['record_id'], ['id'], ondelete='CASCADE')
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('profiles_user_id_fkey'), 'profiles', type_='foreignkey')
    op.create_foreign_key(None, 'profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('service_records', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('service_records', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('service_records_car_id_fkey'), 'service_records', type_='foreignkey')
    op.create_foreign_key(None, 'service_records', 'cars', ['car_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'service_records', type_='foreignkey')
    op.create_foreign_key(op.f('service_records_car_id_fkey'), 'service_records', 'cars', ['car_id'], ['id'])
    op.alter_column('service_records', 'car_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('service_records', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(None, 'profiles', type_='foreignkey')
    op.create_foreign_key(op.f('profiles_user_id_fkey'), 'profiles', 'users', ['user_id'], ['id'])
    op.alter_column('profiles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.create_foreign_key(op.f('parts_record_id_fkey'), 'parts', 'service_records', ['record_id'], ['id'])
    op.alter_column('parts', 'record_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'cars', type_='foreignkey')
    op.create_foreign_key(op.f('cars_owner_id_fkey'), 'cars', 'users', ['owner_id'], ['id'])
    op.alter_column('cars', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
